// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/20/2024, 3:06:09 PM
const configMerger = require("/Users/joshmasen/Developer/personal/joshua-masen-nuxt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/joshmasen/Developer/personal/joshua-masen-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joshmasen/Developer/personal/joshua-masen-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joshmasen/Developer/personal/joshua-masen-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joshmasen/Developer/personal/joshua-masen-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joshmasen/Developer/personal/joshua-masen-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joshmasen/Developer/personal/joshua-masen-nuxt/plugins/**/*.{js,ts,mjs}","/Users/joshmasen/Developer/personal/joshua-masen-nuxt/composables/**/*.{js,ts,mjs}","/Users/joshmasen/Developer/personal/joshua-masen-nuxt/utils/**/*.{js,ts,mjs}","/Users/joshmasen/Developer/personal/joshua-masen-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/joshmasen/Developer/personal/joshua-masen-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/joshmasen/Developer/personal/joshua-masen-nuxt/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["19"] = "/Users/joshmasen/Developer/personal/joshua-masen-nuxt/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
